### ISSUE TITLE
Same latest version across different regions?

### ISSUE THREAD

**Issue by mazzy89** [GoogleCloudPlatform/terraform-google-examples#7]
Is it safe this approach?
https://github.com/GoogleCloudPlatform/terraform-google-examples/blob/master/example-gke-k8s-multi-region/gke-regional/main.tf#L45

I mean different regions point to the same latest version of the container engine? If not then this approach is a bit dangerous because you could end up to retrieve different versions and so different cluster versions for region

**Comment by danisla** [comment]
You should definitely set the `var.master_version` in a production use case. 

The example uses the latest version so that it continues working as GKE releases new versions and deletes old ones.
